version: "3.8"
services:
  webapp:
    build: .
    container_name: my-webapp
    volumes:
      - webapp-uploads:/app/uploads
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  webapp-uploads:

networks:
  app-network:
