version: "3.8"

services:
  nginx:
    image: nginx:latest
    # Alternative: build your own image if you need additional tools
    # build:
    #   context: .
    #   dockerfile: dockerfile
    #   args:
    #     NGINXVER: alpine
    #     USER_ID: 1010
    #     USER_NAME: appuser
    #     GROUP_ID: 1010
    #     GROUP_NAME: appgroup
    #     APP_PORT: 8080
    #     HOST: localhost
    #     LOCAL_URL: http://localhost
    #     APP_ENV: production
    #     BASH_SHELL: /bin/bash
    #     APP_DIR: /app
    #     MOUNT1: /app/data
    #     MOUNT2: /app/logs

    container_name: my-app-project
    hostname: app-project

    labels:
      - "maintainer=farajassulai"
      - "app=front-end"

    environment:
      NGINXVER: alpine
      USER_ID: "1010"
      USER_NAME: appuser
      GROUP_ID: "1010"
      GROUP_NAME: appgroup
      APP_PORT: "8080"
      HOST: localhost
      LOCAL_URL: http://localhost
      APP_ENV: production
      BASH_SHELL: /bin/bash
      APP_DIR: /app
      MOUNT1: /app/data
      MOUNT2: /app/logs
      BACKEND_HOST: database
      TZ: Europe/Paris # Fixed: GMT+2 is not a valid timezone

    networks:
      - my-app-network

    dns:
      - 1.1.1.1
      - 8.8.8.8

    ports:
      - "8080:80" # Fixed: nginx listens on port 80 by default, not 8080

    volumes:
      - /app/logs:/app/logs:ro
      - /app/data:/app/data:ro

    tmpfs:
      - /var/cache/nginx:rw,size=50m,mode=755
      - /var/run:rw,size=50m,mode=755
      - /tmp:rw,size=50m,mode=1777

    # Fixed: Moved mem_limit and cpus to top level for Compose 3.8
    mem_limit: 1g
    mem_reservation: 512m
    cpus: 0.5

    # Fixed: Moved ulimits to top level
    ulimits:
      nfile:
        soft: 1024
        hard: 65536
      nproc:
        soft: 1024
        hard: 4096

    # Fixed: Healthcheck checks nginx default port 80 inside container
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://localhost:80/ || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
        compress: "true"

    security_opt:
      - "no-new-privileges:true"

    cap_drop:
      - ALL

    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

    read_only: true

    user: "1010:1010"

    restart: unless-stopped

    working_dir: /app

networks:
  my-app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
