version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: wordpress-db
    restart: always
    volumes:
      - wordpress-db:/var/lib/mysql
    env_file:
      - .env
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - wordpress-content:/var/www/html/wp-content

volumes:
  wordpress-db:
  wordpress-content:
