services:
  python_flask:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.9
        USERID: 1000
        USERNAME: appuser
        GROUPID: 1000
        GROUPNAME: appgroup
        APP_PORT: 5000
        APP_VER: production

    container_name: python_flask_project
    hostname: app-hostname

    labels:
      - "maintainer=farajassulai@gmail.com"
      - "app=python_flask_project"
      - "type=python_flask"

    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      ENVIRONMENT: production
      PORT: 5000
      TZ: GMT+2

    networks:
      - python_flask_project-network

    dns:
      - 1.1.1.1
      - 8.8.8.8

    ports:
     - "5000:5000"

    volumes:
      - app_data:/app/data:rw
      - app_logs:/app/logs:rw

    # Resource limits - using deploy syntax for modern compose
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.25"
        reservations:
          memory: 256M

    ulimits:
      nofile:
        soft: 1024
        hard: 4096
      nproc:
        soft: 512
        hard: 1024

    # Healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"

    security_opt:
      - "no-new-privileges:true"

    # Minimal capabilities
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

    # Tmpfs mounts for temporary directories
    tmpfs:
      - /tmp:rw,size=10m,mode=1777
      - /run:rw,size=10m,mode=1777

    # Run as non-privileged user
    user: "1000:1000"

    # Container restart policy
    restart: unless-stopped

    # Working directory
    working_dir: /app

# Define named volumes
volumes:
  app_data:
    driver: local
  app_logs:
    driver: local

networks:
  python_flask_project-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24