version: '3.8'
services:
  sqlite:
    build: .
    container_name: sqlite-demo
    volumes:
      - db-volume:/data
    env_file:
      - .env
    command: ["sqlite3", "$DB_FILE"]

volumes:
  db-volume:
